name: Run Unit Tests on PR

on:
  pull_request:
    branches:
      - main
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
